### ISSUE TITLE
404s when clicking through to doctor detail pages

### ISSUE THREAD

**Issue by jamesbloor** [Kentico/training-kentico-k12#19]
### Expected result

List of doctors should link through to the detail page for the specific doctor.

### Additional context

When running the code 'as is' without making any changes, the list of doctors does not link through to the detail pages properly.

### Resources

![image](https://user-images.githubusercontent.com/6383250/52433458-bb934380-2ad2-11e9-9657-296d572d4d2e.png)

![image](https://user-images.githubusercontent.com/6383250/52433258-445daf80-2ad2-11e9-823c-ddec562452d5.png)

* http://localhost/kentico12_medioclinic/en-us/doctors

**Comment by eugene-cp** [comment]
@jamesbloor found where the issue is, previous versions had the NodeGuid automatically added to columns returned but when I submitted my pull request, NodeGuid is not returned by default.  Adding it back in a new PR.
