### ISSUE TITLE
Section controller's implementation breaks naming convention

### ISSUE THREAD

**Issue by lukas-xb** [Kentico/training-kentico-k12#29]
### Brief bug description

What went wrong?
The identifier at [TwoColumnFourtySixtySectionController](https://github.com/Kentico/training-kentico-k12/blob/builders/MedioClinic/Controllers/Sections/TwoColumnFourtySixtySectionController.cs) - _MedioClinic.SectionFourtySixty.TwoColumn_ breaks the naming convention set for the project, (e.g., MedioClinic.Section.TwoColumnSixtyFourty).

**Comment by JanLenoch** [comment]
Fixed via https://github.com/Kentico/training-kentico-k12/commit/2877ac975167b647164a43283ac1dc5decffce0d#diff-c6cfe4591f46eaf956a12ce37a083cd5
