### ISSUE TITLE
Issues with getting the database to restore in SSMS

### ISSUE THREAD

**Issue by dpolomis** [Kentico/training-kentico-k12#34]
Im having issues getting the database file that was included to restore on the current version of SSMS. Any help would be greatly appreciated. 
![Capture](https://user-images.githubusercontent.com/50966210/58907757-84c1e880-86d4-11e9-959e-0adcb016f8c8.PNG)

**Comment by JanLenoch** [comment]
Hello @dpolomis ,

you have an older version of SQL Server than that we've used to create the backup.

I've created .sql files where the database creation is scripted. You should be able to restore the database this way. I've added the files to both "master" and "builders" branches (representing course modules), into the Db subfolder.

You can simply open the .sql file in SSMS and hit F5 to create the MedioClinic database.

Please let me know if it works with your version.

**Comment by dpolomis** [comment]
@JanLenoch Once I extracted the new Db folder, there is indeed a new file but it is still in the format of a .bak file and not a .sql file. what am I missing?

**Comment by JanLenoch** [comment]
In both the "master" and the "builders" branches, there is a new MedioClinicSqlScript.zip file.

(The .sql files contain all database data, hence that .zip file.)

**Comment by JanLenoch** [comment]
Oh, I'm sorry, I really packed a wrong file into that .zip archive. Just a sec ...

**Comment by dpolomis** [comment]
@JanLenoch No worries lol,  I was just very confused to why I couldn't find the files that you said got dropped in the project

**Comment by JanLenoch** [comment]
You can go ahead and try again now.

**Comment by dpolomis** [comment]
@JanLenoch All good, thanks
