### ISSUE TITLE
Unnecessary exception in Constructor

### ISSUE THREAD

**Issue by Enngage** [Kentico/training-kentico-k12#36]
I believe that having:

```
UserManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
SignInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
 AuthenticationManager = authenticationManager ?? throw new ArgumentNullException(nameof(authenticationManager));
ErrorHelperService = errorHelperService ?? throw new ArgumentNullException(nameof(errorHelperService));
LocalizationService = localizationService ?? throw new ArgumentNullException(nameof(localizationService));
AvatarRepository = avatarRepository ?? throw new ArgumentNullException(nameof(avatarRepository));
``` 

is not necessary as DI container should throw an exception if it cannot instantiate class and thus it should never reach constructor. 

I would suggest veryfing this and probably removing the exceptions from constructors.

**Comment by JanLenoch** [comment]
My aim was to foster OO encapsulation and not rely on constructor caller's implementation. What do you think, @Enngage ?

**Comment by JanLenoch** [comment]
Well, after a quick spike on that topic, this [SO thread](https://stackoverflow.com/a/18295691/4074527) (together with a [Microsoft DevBlog post](https://devblogs.microsoft.com/aspnet/dependency-injection-in-asp-net-vnext/)) came to support my idea (of OO encapsulation). Closing.
