### ISSUE TITLE
Rename ViewBagMessage view / action

### ISSUE THREAD

**Issue by Enngage** [Kentico/training-kentico-k12#37]
The ViewbagMessage is not actually using ViewBag and has nothing to do with it (which is a good thing) so I would avoid confusion and renamed it to something more appropriate (e.g. MessageView ...)

**Comment by JanLenoch** [comment]
Refactored via https://github.com/Kentico/training-kentico-k12/commit/d17d0ce47604ee18d1a187b7a3da54b88fa6f90b
