### ISSUE TITLE
Please separate services from repository

### ISSUE THREAD

**Issue by dnistreanu** [Kentico/training-kentico-k12#40]
Please separate the services from the repository. You were talking about MVC best practices when implementing Repository instead of using generated providers. 

But an even more important best practice is to separate the service layer from the data layer. Which is clearly ignored here.

**Comment by JanLenoch** [comment]
Hi @dnistreanu ,

thanks for your point, however, I'm not sure what exact kind of separation you mean. Could you perhaps expand on your idea a bit more?

Thanks!

**Comment by JanLenoch** [comment]
No response whatsoever. Closing.
