### ISSUE TITLE
SocialLinkDto doesn't use the IDto interface.

### ISSUE THREAD

**Issue by ArjanvHugten** [Kentico/training-kentico-k12#41]
SocialLinkDto doesn't implement the IDto interface like the other DTO classes. :)

https://github.com/Kentico/training-kentico-k12/blob/49fda54b52e23620255237d97bc3480986667d2e/Business/Dto/Social/SocialLinkDto.cs#L5

Doesn't have extra functionality but would make it more consistent.

**Comment by JanLenoch** [comment]
Hi @ArjanvHugten , well spotted! I'll change that.
