### ISSUE TITLE
Where can I find the starting site to follow along the tutorials 

### ISSUE THREAD

**Issue by ecnerwal1234** [Kentico/training-kentico-k12#45]
I am trying to follow along the tutorials, but the only version of the site I can find is the completed one.  Is there a way to download a version of the site that matches up with the starting point of the tutorials?  It doesn't appear to be a basic kentico installation,

**Comment by ecnerwal1234** [comment]
Never mind, I see that it is based off of the standard installation.  Wording in the tutorials were confusing.

**Comment by JanLenoch** [comment]
Hello @ecnerwal1234 , thanks for letting us know. We'll revisit the initial parts of the course so that it is clearer what to do to start.
