### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by ecnerwal1234** [Kentico/training-kentico-k12#46]
I'm at the part in the tutorial where I should be able to see the home page.  But I get this error.

Could not load file or assembly 'DotNetOpenAuth.Core, Version=4.1.0.0, Culture=neutral, PublicKeyToken=2780ccd10d57b246' or one of its dependencies. The system cannot find the file specified.

**Comment by ecnerwal1234** [comment]
![errors](https://user-images.githubusercontent.com/6483075/71990888-304e9080-3202-11ea-8721-4d77bd32cad8.PNG)

**Comment by ecnerwal1234** [comment]
I also have 5 warnings in Visual Studio

**Comment by ecnerwal1234** [comment]
I believe the warnings started when I added the Business project.

**Comment by JanLenoch** [comment]
Hello @ecnerwal1234 , 

in the Business project, the DotNetOpenAuth.dll assembly is a deeper dependency of the Kentico.AspNet.Mvc.Libraries NuGet package. In the MedioClinic project, it is a dependency of the Kentico.AspNet.Mvc package.

I'd recommend double-checking that you reference these parent NuGet packages from within your projects, both of them having the same version (eg. 12.0.52). If you have these parent packages installed in your projects, I'd recommend removing them and installing again. Then, I'd do a full solution rebuild.

Hope that helps. Please let me know if it does. Thanks.

**Comment by ecnerwal1234** [comment]
Removing and re-adding the packages helped.  I also had to remove the dontnetopenauth package that I had added in my initial steps to solve the problem.

**Comment by JanLenoch** [comment]
On a side note, what made you to add that package in the initial steps? I can't seem to imagine any reason to do so. It should be added just as part of the above parent packages.

Just curious. :)

**Comment by ecnerwal1234** [comment]
I had a warning that mentioned the DotNetOpenAuth so in trying to get that message to go away I tried installing it.

I've been using kentico for 8 years now and no how to use the portal model really well, this is my first time trying to learn MVC, so I really have no idea what I am doing.

**Comment by JanLenoch** [comment]
Oh, don't worry, you'll master MVC in no time.

You may be interested in taking the general MVC courses from Pluralsight that we refer to from our course intro. They are made by K. Scott Allen, who is a teacher-genius IMO.

The [first one](https://www.pluralsight.com/courses/mvc4-building) is a zero-to-hero course based on MVC4.
The [second one](https://www.pluralsight.com/courses/aspdotnet-mvc5-fundamentals) (which is for free), is a delta for changes made in MVC5.

In the first one, you can skip the Entity Framework part as Kentico NuGet packages take over the role of the DAL layer instead.

Hope it helps.
