### ISSUE TITLE
No Default Web Site is present in Local IIS.  

### ISSUE THREAD

**Issue by whiteleyj** [Kentico/training-kentico-k12#51]
Just a quick 'up and running' nit-pick, but my Local IIS either didn't come with a "Default Web Site" or I deleted it years ago when I first installed it.  I've been used to setting my Kentico sites up like they would appear on production.  I'd normally use admin.medioclinic.develop, and www.medioclinic.develop are my usual local development names, and attempting to do this on the training had some bad results and caused me to have to start back over from the begining.

It would be nice to have some better documentation or at least a link to how to set that up on the readme.md like the following:

Open IIS and find the website named "Default Web Site" 
If one doesn't exist, you must create one.
Make sure that it's using an app pool named DefaultAppPool
Set the Physical Path: %SystemDrive%\Inetpub\wwwroot
Leave everything else blank and hit ok.

From there right click the "Default Web Site" and click add application.
Add the physical path of the CMS directory in this project.  Set alias to "Kentico12_Admin"
Repeat the above process for the MedioClinic folder with an alias of "Kentico12_MedioClinic"

Thanks!

**Comment by JanLenoch** [comment]
Hello @whiteleyj , thanks for your suggestion! In our trainings, we put emphasis on Kentico features, with less focus on explaining details of how ASP.NET works, as well as how to do the basic configuration of IIS.

That being said, I'm not sure that most developers need guidance in terms of how to restore the default IIS configuration on their developer machine.

I'm personally happy you've given us this feedback as it broadens my knowledge of what sort of issues our customers may run into. However, I'm afraid such instructions deal with a corner case that is less usual on developer machines.

Jan
